### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by lashkhi**
Added description on how to run example projects without Carthage

### CODE REVIEW

**Comment by jbrophy17** [comment]
Hi @lashkhi thanks for the PR! Before I can merge this, can you sign the [Uber CLA](http://t.uber.com/cla)? After that,  could you make this PR against the current development branch (dev-0.5.x)? Thanks!

**Comment by lashkhi** [comment]
Hi! Wow! Thanks for reviewing my pr, I've signed CLA, I guess I'll have to make a new pr to dev-0.5 and close this one?

**Comment by jbrophy17** [comment]
Yes please :) sorry for the confusion, we want to keep it clear what is being developed vs what is released

**Comment by lashkhi** [comment]
@jbrophy17 done

**Pull request closed without merging**
