### PR TITLE
Swift 2.0 selector update and little conveinience added... 

### PR DESCRIPTION
**Pull request by Dershowitz011**

### CODE REVIEW

**Comment by arogal** [comment]
Hi there. Can you please submit this agreement: https://docs.google.com/a/uber.com/forms/d/1pAwS_-dA1KhPlfxzYLBqK6rsSWwRwH95OCCZrcsY5rk/viewform

We'll then merge and include it in our next major release. Thank you.

**Comment by Dershowitz011** [comment]
@arogal Done. Is there anything else I could add? Please let me know.

**Comment by arogal** [comment]
Our iOS engineers are currently traveling, but they'll review ASAP and reply with any comments. Thanks!

**Comment by Dershowitz011** [comment]
I suggest this branch be merged(incase it can be merged) as a swift 2.0 branch itself. The selector syntax wont work if a user hasn't updated his xcode to the latest version.

**Comment by jbrophy17** [comment]
Hi @Dershowitz011 thanks for contributing! The selector updates look good, but I haven't had a chance to dig in on your ActionButton commits. Considering these are two very different changes, do you think you could open separate PRs for them? That way I can review the new class and merge in the selector updates in the meantime.

**Pull request closed without merging**
