### PR TITLE
Updated for Swift 2.3/Xcode 8

### PR DESCRIPTION
**Pull request by samwize**
Updated dependency libs with Swift 2.3 support
Fix SDK for Swift 2.3 ♥️

### CODE REVIEW

**Comment by CrossProd** [comment]
Works well. I hope this is merged soon!

**Comment by jbrophy17** [comment]
Thanks for the PR! A few things before I can merge this:
1. Can you sign the  [Uber CLA](http://t.uber.com/cla)? 
2. I have a swift-2.3-dev branch up currently, think you could make this PR agains that branch instead? I want to make sure everything is working there for 2.3

**Comment by samwize** [comment]
I do not have anything new to add to the swift-2.3-dev branch. Thanks for creating the branch.

**Comment by jbrophy17** [comment]
Oh sorry about that! Thanks for contributing! Were you able to successfully run tests? I'm running into some issues with the simulators & entitlements for xcode 8

**Comment by samwize** [comment]
I have tests breaking in `OAuthTests`, and also fatal error when `KeychainWrapper` object is being unwrapped to `AccessToken`.

Didn't see any issues on entitlements though.

**Pull request closed without merging**
