### PR TITLE
Update: selectors syntax

### PR DESCRIPTION
**Pull request by lesyk**

### CODE REVIEW

**Comment by jbrophy17** [comment]
Hi @lesky thanks for the PR. Haven't had a chance to look through it in depth yet but had an initial questions. Is it necessary to prefix the selector method with the class? i.e. can't you just say `#selector(method)` rather than `#selector(foo.method)`?

Other than that, I just need to verify that you got em all :)

**Comment by lesyk** [comment]
You know that you always misspell my name? @lesky != @lesyk

**Comment by jbrophy17** [comment]
*facepalm* 
Sorry about that! 
(and sorry other person I've been mentioning)

**Comment by lesyk** [comment]
about #selector(method) rather than #selector(foo.method), Xcode this that more specific is better, but for you I can do your way @jbrophy1🎱

**Comment by jbrophy17** [comment]
Sorry for the delay, everything looks good here

**Pull request merged**
